name: sim_cam
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=openblas
  - bottleneck=1.3.5=py37h7deecbd_0
  - ca-certificates=2024.12.31=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.1=h3535a68_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numexpr=2.8.4=py37hd2a5715_0
  - openssl=1.1.1w=h7f8727e_0
  - pandas=1.3.5=py37h8c16a72_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.7=py37h06a4308_0
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.2=py37h540881e_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==1.4.0
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - altair==5.0.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - argcomplete==3.1.2
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - asyncer==0.0.2
      - asynctest==0.13.0
      - attrs==24.2.0
      - backcall==0.2.0
      - bagpy==0.5
      - bitarray==2.9.3
      - bitstring==4.1.4
      - boto==2.49.0
      - cachetools==5.5.2
      - catkin-pkg==1.0.0
      - cffi==1.15.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - coloredlogs==15.0.1
      - crcmod==1.7
      - cryptography==45.0.6
      - cv-bridge==1.13.0.post0
      - cycler==0.11.0
      - decorator==5.1.1
      - dill==0.3.7
      - dm-tree==0.1.8
      - docutils==0.20.1
      - etils==0.9.0
      - exceptiongroup==1.2.2
      - fastapi==0.103.2
      - fasteners==0.20
      - ffmpy==0.3.2
      - filelock==3.12.2
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - gast==0.4.0
      - gcs-oauth2-boto-plugin==3.2
      - gnupg==2.3.1
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - googleapis-common-protos==1.70.0
      - gradio==3.34.0
      - gradio-client==0.2.6
      - grpcio==1.62.3
      - gsutil==5.31
      - h11==0.14.0
      - h5py==3.8.0
      - httpcore==0.17.3
      - httplib2==0.20.4
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - idna==3.10
      - imagehash==4.3.2
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - ipython==7.34.0
      - jedi==0.19.2
      - jinja2==3.0.3
      - joblib==1.3.2
      - jsonschema==4.17.3
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - linkify-it-py==2.0.3
      - llvmlite==0.39.1
      - markdown==3.4.4
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mediapy==1.1.2
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - natsort==8.4.0
      - networkx==2.6.3
      - numba==0.56.4
      - numpy==1.21.6
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - onnxruntime==1.14.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.3.0
      - orjson==3.9.7
      - packaging==24.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.0.0
      - pluggy==1.2.0
      - pooch==1.8.2
      - promise==2.3
      - prompt-toolkit==3.0.48
      - protobuf==3.19.6
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - py3rosmsgs==1.18.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybullet==3.2.6
      - pycparser==2.21
      - pycryptodomex==3.21.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pygments==2.17.2
      - pymatting==1.1.14
      - pyopenssl==25.1.0
      - pyparsing==3.1.4
      - pyrsistent==0.19.3
      - pyserial==3.5
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.8
      - pyu2f==0.1.5
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - rembg==2.0.40
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - retry-decorator==1.1.1
      - rospkg==1.5.1
      - rsa==4.7.2
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.12.2
      - semantic-version==2.10.0
      - setuptools-scm==7.1.0
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.27.0
      - sympy==1.10.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-datasets==4.8.2
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.12.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - tqdm==4.67.1
      - traitlets==5.9.0
      - trimesh==4.4.1
      - typing-extensions==4.7.1
      - uc-micro-py==1.0.3
      - urllib3==2.0.7
      - uvicorn==0.22.0
      - watchdog==3.0.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.15.0
